# Generated by Django 5.2.7 on 2025-10-31 15:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the data source', max_length=200)),
                ('source_type', models.CharField(choices=[('SATELLITE', 'Satellite Imagery'), ('WEATHER_STATION', 'Weather Station'), ('SENSOR', 'Environmental Sensor'), ('HISTORICAL', 'Historical Data'), ('REALTIME', 'Real-time Data')], help_text='Type of data source', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Geographic location of the data source', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude coordinate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude coordinate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this source is currently active')),
                ('description', models.TextField(blank=True, help_text='Additional description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_data_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_path', models.FileField(help_text='Path to uploaded file', upload_to='data_uploads/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('errors', models.TextField(blank=True, help_text='Processing errors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Upload',
                'verbose_name_plural': 'Data Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='When the data was recorded')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperature in Celsius', max_digits=6, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Humidity percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('precipitation', models.DecimalField(blank=True, decimal_places=2, help_text='Precipitation in mm', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, help_text='Wind speed in m/s', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('wind_direction', models.DecimalField(blank=True, decimal_places=1, help_text='Wind direction in degrees', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('atmospheric_pressure', models.DecimalField(blank=True, decimal_places=2, help_text='Atmospheric pressure in hPa', max_digits=8, null=True)),
                ('co2_level', models.DecimalField(blank=True, decimal_places=2, help_text='CO2 level in ppm', max_digits=8, null=True)),
                ('pm25', models.DecimalField(blank=True, decimal_places=2, help_text='PM2.5 concentration', max_digits=6, null=True)),
                ('pm10', models.DecimalField(blank=True, decimal_places=2, help_text='PM10 concentration', max_digits=6, null=True)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, help_text='Data quality score (0-1)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this data point')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_climate_data', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_data', to='data.datasource')),
            ],
            options={
                'verbose_name': 'Climate Data',
                'verbose_name_plural': 'Climate Data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='data_climat_timesta_60ad6b_idx'), models.Index(fields=['data_source', 'timestamp'], name='data_climat_data_so_bf18ac_idx')],
            },
        ),
    ]
