# Generated by Django 5.2.7 on 2025-11-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatedata',
            name='temp_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum temperature in Celsius', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='climatedata',
            name='temp_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum temperature in Celsius', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='climatedata',
            name='weather_description',
            field=models.CharField(blank=True, help_text='Weather condition description (e.g., rain, sunny, cloudy)', max_length=100),
        ),
    ]
