# Generated by Django 5.2.7 on 2025-11-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_climatedata_temp_max_climatedata_temp_min_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climatedata',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp'], 'verbose_name': 'Climate Data', 'verbose_name_plural': 'Climate Data'},
        ),
    ]
