# Generated by Django 5.2.7 on 2025-11-01 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the model', max_length=200)),
                ('model_type', models.CharField(choices=[('ANOMALY', 'Anomaly Detection'), ('TEMPERATURE', 'Temperature Forecast'), ('CLIMATE', 'Climate Prediction'), ('AIR_QUALITY', 'Air Quality Forecast')], help_text='Type of ML model', max_length=20)),
                ('status', models.CharField(choices=[('TRAINING', 'Training'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('OUTDATED', 'Outdated')], default='READY', help_text='Current status of the model', max_length=20)),
                ('model_file', models.FileField(help_text='Path to the trained model file', upload_to='ml_models/')),
                ('model_path', models.CharField(help_text='Full path to model file for loading', max_length=500)),
                ('accuracy_score', models.FloatField(blank=True, help_text='Model accuracy score (0-1)', null=True)),
                ('f1_score', models.FloatField(blank=True, help_text='F1 score for classification models', null=True)),
                ('mse_score', models.FloatField(blank=True, help_text='Mean Squared Error for regression models', null=True)),
                ('training_data_start', models.DateTimeField(blank=True, help_text='Start date of training data', null=True)),
                ('training_data_end', models.DateTimeField(blank=True, help_text='End date of training data', null=True)),
                ('last_trained', models.DateTimeField(blank=True, help_text='When the model was last trained', null=True)),
                ('config', models.JSONField(default=dict, help_text='Model configuration parameters (JSON)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model is available for predictions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ml_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('evaluation_start', models.DateTimeField()),
                ('evaluation_end', models.DateTimeField()),
                ('total_predictions', models.PositiveIntegerField(default=0)),
                ('correct_predictions', models.PositiveIntegerField(default=0)),
                ('false_positives', models.PositiveIntegerField(default=0)),
                ('false_negatives', models.PositiveIntegerField(default=0)),
                ('model_drift_score', models.FloatField(blank=True, help_text='Measure of how much the model has drifted from training data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_evaluations', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ai_models.mlmodel')),
            ],
            options={
                'verbose_name': 'ML Model Metrics',
                'verbose_name_plural': 'ML Model Metrics',
                'ordering': ['-created_at'],
                'unique_together': {('model', 'evaluation_start', 'evaluation_end')},
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('ANOMALY_SCORE', 'Anomaly Score'), ('TEMPERATURE_FORECAST', 'Temperature Forecast'), ('CLIMATE_TREND', 'Climate Trend'), ('AIR_QUALITY_FORECAST', 'Air Quality Forecast')], help_text='Type of prediction made', max_length=30)),
                ('prediction_value', models.FloatField(help_text='The predicted value')),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score for the prediction (0-1)', null=True)),
                ('prediction_range', models.JSONField(default=dict, help_text='Prediction range/confidence intervals (JSON)')),
                ('target_timestamp', models.DateTimeField(help_text='Timestamp the prediction is for')),
                ('input_data', models.JSONField(default=dict, help_text='Input data used for prediction (JSON)')),
                ('actual_value', models.FloatField(blank=True, help_text='Actual observed value (for validation)', null=True)),
                ('error_margin', models.FloatField(blank=True, help_text='Prediction error margin', null=True)),
                ('is_anomaly', models.BooleanField(default=False, help_text='Whether this prediction indicates an anomaly')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this prediction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('climate_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_predictions', to='data.climatedata')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_predictions', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ai_models.mlmodel')),
            ],
            options={
                'verbose_name': 'ML Prediction',
                'verbose_name_plural': 'ML Predictions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model', 'target_timestamp'], name='ai_models_m_model_i_895a4e_idx'), models.Index(fields=['prediction_type', 'created_at'], name='ai_models_m_predict_87663c_idx')],
            },
        ),
    ]
