# Generated by Django 5.2.7 on 2025-10-31 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Widget title', max_length=200)),
                ('widget_type', models.CharField(choices=[('CHART', 'Chart'), ('GAUGE', 'Gauge'), ('TABLE', 'Data Table'), ('MAP', 'Map View'), ('METRIC', 'Key Metric')], help_text='Type of visualization widget', max_length=20)),
                ('data_source', models.CharField(choices=[('TEMPERATURE', 'Temperature Data'), ('HUMIDITY', 'Humidity Data'), ('PRECIPITATION', 'Precipitation Data'), ('WIND', 'Wind Data'), ('AIR_QUALITY', 'Air Quality Data'), ('CUSTOM', 'Custom Query')], help_text='Source of data for this widget', max_length=20)),
                ('position_x', models.PositiveIntegerField(default=0, help_text='X position on dashboard grid')),
                ('position_y', models.PositiveIntegerField(default=0, help_text='Y position on dashboard grid')),
                ('width', models.PositiveIntegerField(default=4, help_text='Widget width in grid units')),
                ('height', models.PositiveIntegerField(default=3, help_text='Widget height in grid units')),
                ('config', models.JSONField(default=dict, help_text='Widget-specific configuration (chart type, filters, etc.)')),
                ('refresh_interval', models.PositiveIntegerField(default=300, help_text='Auto-refresh interval in seconds (0 = no auto-refresh)')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this widget is visible to all users')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this widget is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Dashboard', help_text='Dashboard title', max_length=200)),
                ('layout_config', models.JSONField(default=dict, help_text='Dashboard layout configuration')),
                ('is_default', models.BooleanField(default=True, help_text="Whether this is the user's default dashboard")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Dashboard',
                'verbose_name_plural': 'User Dashboards',
            },
        ),
    ]
