# Generated by Django 5.2.7 on 2025-10-31 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the alert threshold', max_length=200)),
                ('metric', models.CharField(choices=[('TEMPERATURE', 'Temperature (°C)'), ('HUMIDITY', 'Humidity (%)'), ('PRECIPITATION', 'Precipitation (mm)'), ('WIND_SPEED', 'Wind Speed (m/s)'), ('CO2_LEVEL', 'CO2 Level (ppm)'), ('PM25', 'PM2.5'), ('PM10', 'PM10')], help_text='Climate metric to monitor', max_length=20)),
                ('condition', models.CharField(choices=[('ABOVE', 'Above threshold'), ('BELOW', 'Below threshold'), ('EQUALS', 'Equals threshold')], help_text='Condition for triggering alert', max_length=10)),
                ('threshold_value', models.DecimalField(decimal_places=2, help_text='Threshold value for the metric', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this threshold is active')),
                ('description', models.TextField(blank=True, help_text='Description of this threshold')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alert_thresholds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Threshold',
                'verbose_name_plural': 'Alert Thresholds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Feedback subject', max_length=200)),
                ('category', models.CharField(choices=[('BUG', 'Bug Report'), ('FEATURE', 'Feature Request'), ('DATA', 'Data Issue'), ('USABILITY', 'Usability Issue'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the feedback')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('resolution', models.TextField(blank=True, help_text='Resolution details')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feedback', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_feedback', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('notification_type', models.CharField(choices=[('ALERT', 'Climate Alert'), ('SYSTEM', 'System Notification'), ('DATA', 'Data Processing'), ('SECURITY', 'Security Alert')], default='SYSTEM', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the notification was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_threshold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.alertthreshold')),
                ('climate_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='data.climatedata')),
                ('recipients', models.ManyToManyField(help_text='Users who should receive this notification', related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
